name: DevOps CI/CD

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build -x test --no-daemon

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test --no-daemon

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Connect and deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Conexión exitosa hacia EC2"

            cd GRUPO2_N_DEVOPS

            git pull origin master

            docker stop grupo2-backend-container || true
            docker rm grupo2-backend-container || true

            docker build -t grupo2-backend .

            docker run -d \
              --name grupo2-backend-container \
              -p 8080:8080 \
              -e DB_HOST=$DB_HOST \
              -e DB_PORT=$DB_PORT \
              -e DB_NAME=$DB_NAME \
              -e DB_USER=$DB_USER \
              -e DB_PASSWORD=$DB_PASSWORD \
              grupo2-backend
