name: DevOps CI/CD

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build -x test --no-daemon

      - name: Deploy placeholder
        run: echo "Deploy a EC2 pendiente"